---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
birth_rate <- read.csv('birth-rate.csv')
birth_rate_yearly <- read.csv('birth-rates-yearly.csv')
crime_rate <- read.csv('crimerates-by-state-2005.csv')
```

```{r}
library(ggplot2)
states <- crime_rate[(crime_rate$state != 'United States') & (crime_rate$state != 'District of Columbia'),]
ggplot(states, aes(x= population, y= murder)) + geom_point(color= 'darkred')  + ggtitle('Scatterplot in R', sub = 'Comarison of Murder to Population Size') + theme(panel.background = element_blank(),panel.border =element_blank())
```

```{r}
ggplot(states, aes(x= population, y= motor_vehicle_theft, size= murder)) + geom_point(color='darkred', alpha= .3) + scale_size_continuous(range = c(.1, 10)) + theme(panel.background = element_blank(), panel.border =element_blank(), legend.box.background  = element_blank(), legend.position = 'right') + ggtitle('Bubble Chart in R', sub= 'Effect of Motor Vehicle Theft and Population on Murder') + ylab('motor vehicle theft')
```


```{r}

ggplot(crime_rate) + geom_density(aes(x= forcible_rape, col= 'rape'), size=1) + geom_density(aes(x= murder, color= 'murder'), size=1) + ggtitle('Density Plot in R', sub= 'Comparing the distribution of murde and rape rates') + xlab('rate') + ylab('')
```

```{r}

```

